apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: multi-agent-api-hpa
spec:
  # Targets the Deployment defined in deployment.yaml
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: multi-agent-api-deployment
  minReplicas: 2 # Always keep at least 2 instances running
  maxReplicas: 10 # Scale up to a maximum of 10 instances under heavy load
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Scale up if average CPU usage across all pods exceeds 70%